export interface GalleryPhoto {
  id: string;
  placeholderNumber: number;
  title: string;
  edition: string;
  category: "Pitch & Keynote" | "Hackathons" | "Expos & Bidding" | "Competitions" | "Moments & Gala";
  date: string;
  description: string;
  stats?: string;
  image: {
    src: string;
    alt: string;
  };
}

export const GALLERY_CATEGORIES = [
  "All Moments",
  "Pitch & Keynote",
  "Hackathons",
  "Expos & Bidding",
  "Competitions",
  "Moments & Gala",
] as const;

export type GalleryCategory = (typeof GALLERY_CATEGORIES)[number];

// All 32 camera photos from the Equinox archive
export const PREVIOUS_EVENT_PHOTOS: GalleryPhoto[] = [
  {
    id: "equinox-photo-1",
    placeholderNumber: 1,
    title: "Inaugural Keynote & Lighting Ceremony",
    edition: "Equinox 1.0",
    category: "Pitch & Keynote",
    date: "Equinox Archive",
    description: "Opening ceremonies graced by college leadership, distinguished dignitaries, and startup founders welcoming delegates to Equinox.",
    stats: "Keynote Hall",
    image: {
      src: "/equinox-gallery/photo-1.jpg",
      alt: "Inaugural Keynote & Lighting Ceremony at Equinox",
    },
  },
  {
    id: "equinox-photo-2",
    placeholderNumber: 2,
    title: "Founder Pitch Off & Jury Deliberation",
    edition: "Equinox 1.0",
    category: "Pitch & Keynote",
    date: "Equinox Archive",
    description: "Student founders presenting their innovative solutions to institutional investors and angel syndicate partners.",
    stats: "45+ Pitches",
    image: {
      src: "/equinox-gallery/photo-2.jpg",
      alt: "Founder Pitch Off & Jury Deliberation",
    },
  },
  {
    id: "equinox-photo-3",
    placeholderNumber: 3,
    title: "Auditorium Packed Keynote Session",
    edition: "Equinox 1.0",
    category: "Pitch & Keynote",
    date: "Equinox Archive",
    description: "Over a thousand eager delegates filling the main auditorium to absorb insights from unicorn founders and tech leaders.",
    stats: "1,500+ Attendees",
    image: {
      src: "/equinox-gallery/photo-3.jpg",
      alt: "Auditorium Packed Keynote Session",
    },
  },
  {
    id: "equinox-photo-4",
    placeholderNumber: 4,
    title: "Midnight Hackathon War Room",
    edition: "MetaLoop Hackathon",
    category: "Hackathons",
    date: "Equinox Archive",
    description: "Teams hacking past 2 AM, building breakthrough spatial AR/VR and decentralized apps with mentors on standby.",
    stats: "36-Hour Sprint",
    image: {
      src: "/equinox-gallery/photo-4.jpg",
      alt: "Midnight Hackathon War Room",
    },
  },
  {
    id: "equinox-photo-5",
    placeholderNumber: 5,
    title: "Hardware Lab Prototyping Rush",
    edition: "Inventron Challenge",
    category: "Competitions",
    date: "Equinox Archive",
    description: "Engineers soldering microcontrollers and configuring IoT sensors during the rigorous hardware innovation track.",
    stats: "Rapid Prototyping",
    image: {
      src: "/equinox-gallery/photo-5.jpg",
      alt: "Hardware Lab Prototyping Rush",
    },
  },
  {
    id: "equinox-photo-6",
    placeholderNumber: 6,
    title: "Startup Expo Pavilion Showcase",
    edition: "Equinox Summit",
    category: "Expos & Bidding",
    date: "Equinox Archive",
    description: "Student ventures exhibiting working prototypes, receiving live customer feedback, and connecting with early adopters.",
    stats: "30+ Stalls",
    image: {
      src: "/equinox-gallery/photo-6.jpg",
      alt: "Startup Expo Pavilion Showcase",
    },
  },
  {
    id: "equinox-photo-7",
    placeholderNumber: 7,
    title: "IPL Mock Auction Heated Bidding",
    edition: "IPL Auction",
    category: "Expos & Bidding",
    date: "Equinox Archive",
    description: "Strategy teams crunching analytics, statistical models, and budget limits in the high-stakes bidding war.",
    stats: "₹100 Cr Purse",
    image: {
      src: "/equinox-gallery/photo-7.jpg",
      alt: "IPL Mock Auction Heated Bidding",
    },
  },
  {
    id: "equinox-photo-8",
    placeholderNumber: 8,
    title: "Women in Tech & Leadership Panel",
    edition: "CIE Summit",
    category: "Pitch & Keynote",
    date: "Equinox Archive",
    description: "Trailblazing women leaders in tech and venture capital discussing the next frontier of student-led innovation.",
    stats: "Panel Discussion",
    image: {
      src: "/equinox-gallery/photo-8.jpg",
      alt: "Women in Tech & Leadership Panel",
    },
  },
  {
    id: "equinox-photo-9",
    placeholderNumber: 9,
    title: "Investor One-on-One Office Hours",
    edition: "Equinox 1.0",
    category: "Pitch & Keynote",
    date: "Equinox Archive",
    description: "Curated closed-door feedback sessions between shortlisted teams and venture partners evaluating term sheets.",
    stats: "Angel Round",
    image: {
      src: "/equinox-gallery/photo-9.jpg",
      alt: "Investor One-on-One Office Hours",
    },
  },
  {
    id: "equinox-photo-10",
    placeholderNumber: 10,
    title: "Code Jam Sprint Check-in",
    edition: "MetaLoop Hackathon",
    category: "Hackathons",
    date: "Equinox Archive",
    description: "Mentors reviewing code architecture and API integrations before teams enter the final development phase.",
    stats: "Checkpoint 02",
    image: {
      src: "/equinox-gallery/photo-10.jpg",
      alt: "Code Jam Sprint Check-in",
    },
  },
  {
    id: "equinox-photo-11",
    placeholderNumber: 11,
    title: "Grand Stage Cash Prize Distribution",
    edition: "Equinox 1.0",
    category: "Moments & Gala",
    date: "Equinox Archive",
    description: "The winning team receiving their ceremonial cheque and trophy amidst cheers from the entire congregation.",
    stats: "₹1,50,000 Award",
    image: {
      src: "/equinox-gallery/photo-11.jpg",
      alt: "Grand Stage Cash Prize Distribution",
    },
  },
  {
    id: "equinox-photo-12",
    placeholderNumber: 12,
    title: "Case Study Strategy Presentation",
    edition: "Brand Battles",
    category: "Competitions",
    date: "Equinox Archive",
    description: "Finalist teams dissecting complex market entry scenarios in front of seasoned corporate judges.",
    stats: "Case Finals",
    image: {
      src: "/equinox-gallery/photo-12.jpg",
      alt: "Case Study Strategy Presentation",
    },
  },
  {
    id: "equinox-photo-13",
    placeholderNumber: 13,
    title: "Interactive Robotics Demo Arena",
    edition: "Inventron Challenge",
    category: "Competitions",
    date: "Equinox Archive",
    description: "Autonomous robotics and drone prototypes being tested on obstacle courses in the open innovation arena.",
    stats: "Hardware Track",
    image: {
      src: "/equinox-gallery/photo-13.jpg",
      alt: "Interactive Robotics Demo Arena",
    },
  },
  {
    id: "equinox-photo-14",
    placeholderNumber: 14,
    title: "Collaborative Brainstorming Pods",
    edition: "MetaLoop Hackathon",
    category: "Hackathons",
    date: "Equinox Archive",
    description: "Cross-functional teams mapping wireframes, user journeys, and system schemas on whiteboard glass walls.",
    stats: "Design Sprint",
    image: {
      src: "/equinox-gallery/photo-14.jpg",
      alt: "Collaborative Brainstorming Pods",
    },
  },
  {
    id: "equinox-photo-15",
    placeholderNumber: 15,
    title: "E-Cell Conclave Leadership Round",
    edition: "E-Cell Conclave",
    category: "Moments & Gala",
    date: "Equinox Archive",
    description: "Entrepreneurship leaders from colleges across South India collaborating on inter-institutional ecosystems.",
    stats: "25+ Colleges",
    image: {
      src: "/equinox-gallery/photo-15.jpg",
      alt: "E-Cell Conclave Leadership Round",
    },
  },
  {
    id: "equinox-photo-16",
    placeholderNumber: 16,
    title: "Valedictory Celebrations & Cheers",
    edition: "Equinox 1.0",
    category: "Moments & Gala",
    date: "Equinox Archive",
    description: "Joy, high-fives, and celebration as organizers and participants mark the triumphant conclusion of the summit.",
    stats: "Closing Gala",
    image: {
      src: "/equinox-gallery/photo-16.jpg",
      alt: "Valedictory Celebrations & Cheers",
    },
  },
  {
    id: "equinox-photo-17",
    placeholderNumber: 17,
    title: "Fireside Chat on DeepTech Ventures",
    edition: "CIE Summit",
    category: "Pitch & Keynote",
    date: "Equinox Archive",
    description: "An intimate conversation exploring the commercialization of cutting-edge AI and robotics research.",
    stats: "DeepTech Stage",
    image: {
      src: "/equinox-gallery/photo-17.jpg",
      alt: "Fireside Chat on DeepTech Ventures",
    },
  },
  {
    id: "equinox-photo-18",
    placeholderNumber: 18,
    title: "Speed Networking & Teaming Arena",
    edition: "Equinox Summit",
    category: "Moments & Gala",
    date: "Equinox Archive",
    description: "Developers, designers, and marketers discovering co-founders and finding teammates for the hackathon tracks.",
    stats: "200+ Connects",
    image: {
      src: "/equinox-gallery/photo-18.jpg",
      alt: "Speed Networking & Teaming Arena",
    },
  },
  {
    id: "equinox-photo-19",
    placeholderNumber: 19,
    title: "Product Demo Day Live Reactions",
    edition: "Equinox Expo",
    category: "Expos & Bidding",
    date: "Equinox Archive",
    description: "Audience members and judges interacting firsthand with consumer tech prototypes and SaaS dashboards.",
    stats: "Live Testing",
    image: {
      src: "/equinox-gallery/photo-19.jpg",
      alt: "Product Demo Day Live Reactions",
    },
  },
  {
    id: "equinox-photo-20",
    placeholderNumber: 20,
    title: "Late-Night Debugging Session",
    edition: "MetaLoop Hackathon",
    category: "Hackathons",
    date: "Equinox Archive",
    description: "Tireless developers troubleshooting build pipelines and fine-tuning shader performance in the early dawn.",
    stats: "Git Push Sprint",
    image: {
      src: "/equinox-gallery/photo-20.jpg",
      alt: "Late-Night Debugging Session",
    },
  },
  {
    id: "equinox-photo-21",
    placeholderNumber: 21,
    title: "Stage Lighting & Opening Reveal",
    edition: "Equinox 1.0",
    category: "Moments & Gala",
    date: "Equinox Archive",
    description: "Dramatic laser unveilings and keynote visuals setting an electric tone for the two-day summit.",
    stats: "Mainstage FX",
    image: {
      src: "/equinox-gallery/photo-21.jpg",
      alt: "Stage Lighting & Opening Reveal",
    },
  },
  {
    id: "equinox-photo-22",
    placeholderNumber: 22,
    title: "Mentor Desk One-on-One Reviews",
    edition: "MetaLoop Hackathon",
    category: "Hackathons",
    date: "Equinox Archive",
    description: "Industry veterans offering direct architectural advice, pitch coaching, and production tips to hackers.",
    stats: "Mentorship",
    image: {
      src: "/equinox-gallery/photo-22.jpg",
      alt: "Mentor Desk One-on-One Reviews",
    },
  },
  {
    id: "equinox-photo-23",
    placeholderNumber: 23,
    title: "Bidding War Strategy Room",
    edition: "IPL Auction",
    category: "Expos & Bidding",
    date: "Equinox Archive",
    description: "Team captains conferring under countdown clocks before raising the paddle for marquee player acquisitions.",
    stats: "Tactical Room",
    image: {
      src: "/equinox-gallery/photo-23.jpg",
      alt: "Bidding War Strategy Room",
    },
  },
  {
    id: "equinox-photo-24",
    placeholderNumber: 24,
    title: "Student Innovations Showcase Walk",
    edition: "Equinox Expo",
    category: "Expos & Bidding",
    date: "Equinox Archive",
    description: "Dignitaries and visiting university vice chancellors touring student project exhibits across the atrium.",
    stats: "Campus Walkway",
    image: {
      src: "/equinox-gallery/photo-24.jpg",
      alt: "Student Innovations Showcase Walk",
    },
  },
  {
    id: "equinox-photo-25",
    placeholderNumber: 25,
    title: "High-Energy Final Pitch Defense",
    edition: "Equinox 1.0",
    category: "Pitch & Keynote",
    date: "Equinox Archive",
    description: "Founders deftly defending unit economics, traction metrics, and customer acquisition costs under fire.",
    stats: "Jury Defense",
    image: {
      src: "/equinox-gallery/photo-25.jpg",
      alt: "High-Energy Final Pitch Defense",
    },
  },
  {
    id: "equinox-photo-26",
    placeholderNumber: 26,
    title: "Trophy Moment & Winner Accolades",
    edition: "Equinox 1.0",
    category: "Moments & Gala",
    date: "Equinox Archive",
    description: "Gold medalists hoisting their championship trophies with jubilant smiles in front of flash cameras.",
    stats: "Podium Finish",
    image: {
      src: "/equinox-gallery/photo-26.jpg",
      alt: "Trophy Moment & Winner Accolades",
    },
  },
  {
    id: "equinox-photo-27",
    placeholderNumber: 27,
    title: "Hardware Assembly Under Pressure",
    edition: "Inventron Challenge",
    category: "Competitions",
    date: "Equinox Archive",
    description: "Final wire terminations and microcontroller flashing minutes before the project submission deadline.",
    stats: "Final Assembly",
    image: {
      src: "/equinox-gallery/photo-27.jpg",
      alt: "Hardware Assembly Under Pressure",
    },
  },
  {
    id: "equinox-photo-28",
    placeholderNumber: 28,
    title: "Organizing Committee High-Fives",
    edition: "Equinox Summit",
    category: "Moments & Gala",
    date: "Equinox Archive",
    description: "The student core team and faculty coordinators celebrating another flawless event execution.",
    stats: "CIE Crew",
    image: {
      src: "/equinox-gallery/photo-28.jpg",
      alt: "Organizing Committee High-Fives",
    },
  },
  {
    id: "equinox-photo-29",
    placeholderNumber: 29,
    title: "Keynote Speaker Honor & Memento",
    edition: "Equinox 1.0",
    category: "Pitch & Keynote",
    date: "Equinox Archive",
    description: "College leadership felicitating distinguished guest speakers with handcrafted commemorative mementos.",
    stats: "Speaker Honor",
    image: {
      src: "/equinox-gallery/photo-29.jpg",
      alt: "Keynote Speaker Honor & Memento",
    },
  },
  {
    id: "equinox-photo-30",
    placeholderNumber: 30,
    title: "VR Spatial Experience Live Test",
    edition: "MetaLoop Hackathon",
    category: "Hackathons",
    date: "Equinox Archive",
    description: "Judges testing immersive virtual reality applications built completely from scratch over 36 hours.",
    stats: "Oculus Demo",
    image: {
      src: "/equinox-gallery/photo-30.jpg",
      alt: "VR Spatial Experience Live Test",
    },
  },
  {
    id: "equinox-photo-31",
    placeholderNumber: 31,
    title: "Audience Applause & Ovation",
    edition: "Equinox Summit",
    category: "Moments & Gala",
    date: "Equinox Archive",
    description: "A roaring round of applause as the final pitch of the day concludes with exceptional audience enthusiasm.",
    stats: "Standing Ovation",
    image: {
      src: "/equinox-gallery/photo-31.jpg",
      alt: "Audience Applause & Ovation",
    },
  },
  {
    id: "equinox-photo-32",
    placeholderNumber: 32,
    title: "Equinox Commemorative Cohort Photo",
    edition: "Equinox 1.0",
    category: "Moments & Gala",
    date: "Equinox Archive",
    description: "All participants, judges, mentors, and organizing team gathering on the grand lawn for the official summit photo.",
    stats: "All Cohorts",
    image: {
      src: "/equinox-gallery/photo-32.jpg",
      alt: "Equinox Commemorative Cohort Photo",
    },
  },
];
